# Generated by Django 4.0.2 on 2022-02-07 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('products', models.ManyToManyField(to='product.Product')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
